export const RACK_ERROR_MESSAGE = {
  NOT_AVAILABLE_YET: "RACK_NOT_AVAILABLE_YET",
  INVALID_SKU: "RACK_INVALID_SKU",
  INVALID_QUANTITY: "RACK_INVALID_QUANTITY",
  INSUFFICIENT_BALANCE: "RACK_INSUFFICIENT_BALANCE",
  PURCHASE_ERROR: "RACK_PURCHASE_ERROR",
} as const;
