export const FAN_ERROR_MESSAGE = {
  NOT_AVAILABLE_YET: "FAN_NOT_AVAILABLE_YET",
  INVALID_SKU: "FAN_INVALID_SKU",
  INVALID_QUANTITY: "FAN_INVALID_QUANTITY",
  INSUFFICIENT_BALANCE: "FAN_INSUFFICIENT_BALANCE",
  PURCHASE_ERROR: "FAN_PURCHASE_ERROR",
} as const;
