/** Ported from legacy/server/modules/zerads/zerads.controller.ts (inline logger.warn codes). */
export const ZERADS_ERROR = {
    IP_REJECTED: "ZERADS_IP_REJECTED",
    NO_SECRET_CONFIGURED: "ZERADS_NO_SECRET_CONFIGURED",
    BAD_PASSWORD: "ZERADS_BAD_PASSWORD",
    MISSING_USERNAME: "ZERADS_MISSING_USERNAME",
    INVALID_AMOUNT: "ZERADS_INVALID_AMOUNT",
    NO_CLICKS: "ZERADS_NO_CLICKS",
    USER_NOT_FOUND: "ZERADS_USER_NOT_FOUND",
    USER_BANNED: "ZERADS_USER_BANNED",
    TRANSACTION_FAILED: "ZERADS_TRANSACTION_FAILED",
};
