/** Ported from the exact `Error.message` strings legacy/shop.service.ts throws — callers match on message. */
export const SHOP_ERROR_MESSAGE = {
  MINER_UNAVAILABLE: "Miner unavailable.",
  OUT_OF_STOCK: "Miner out of stock.",
  PURCHASE_LIMIT_REACHED: "Miner purchase limit reached.",
  INSUFFICIENT_BALANCE: "Insufficient balance.",
} as const;

export const SHOP_ERROR_CODE = {
  SHOP_LIST_ERROR: "SHOP_LIST_ERROR",
  SHOP_INVALID_MINER_ID: "SHOP_INVALID_MINER_ID",
  SHOP_INVALID_QUANTITY: "SHOP_INVALID_QUANTITY",
  SHOP_MINER_UNAVAILABLE: "SHOP_MINER_UNAVAILABLE",
  SHOP_OUT_OF_STOCK: "SHOP_OUT_OF_STOCK",
  SHOP_PURCHASE_LIMIT_REACHED: "SHOP_PURCHASE_LIMIT_REACHED",
  SHOP_INSUFFICIENT_BALANCE: "SHOP_INSUFFICIENT_BALANCE",
  SHOP_PURCHASE_ERROR: "SHOP_PURCHASE_ERROR",
  FAN_INVALID_SKU: "FAN_INVALID_SKU",
  FAN_INVALID_QUANTITY: "FAN_INVALID_QUANTITY",
  FAN_NOT_AVAILABLE_YET: "FAN_NOT_AVAILABLE_YET",
  FAN_INSUFFICIENT_BALANCE: "FAN_INSUFFICIENT_BALANCE",
  FAN_PURCHASE_ERROR: "FAN_PURCHASE_ERROR",
  RACK_INVALID_SKU: "RACK_INVALID_SKU",
  RACK_INVALID_QUANTITY: "RACK_INVALID_QUANTITY",
  RACK_NOT_AVAILABLE_YET: "RACK_NOT_AVAILABLE_YET",
  RACK_INSUFFICIENT_BALANCE: "RACK_INSUFFICIENT_BALANCE",
  RACK_PURCHASE_ERROR: "RACK_PURCHASE_ERROR",
  RACE_CONDITION_DETECTED: "RACE_CONDITION_DETECTED",
} as const;

export type ShopErrorCode = (typeof SHOP_ERROR_CODE)[keyof typeof SHOP_ERROR_CODE];

export class ShopPurchaseRejectedError extends Error {
  readonly code?: ShopErrorCode;

  constructor(message: string, code?: ShopErrorCode) {
    super(message);
    this.name = "ShopPurchaseRejectedError";
    this.code = code;
  }
}
