/** Ported from legacy/server/modules/offerwallme/offerwallme.controller.ts (inline error strings → named codes). */
export const OFFERWALLME_ERROR = {
  IP_REJECTED: "OFFERWALLME_IP_REJECTED",
  MISSING_PARAMS: "OFFERWALLME_MISSING_PARAMS",
  BAD_SIGNATURE: "OFFERWALLME_BAD_SIGNATURE",
  INVALID_USER: "OFFERWALLME_INVALID_USER",
  USER_NOT_FOUND: "OFFERWALLME_USER_NOT_FOUND",
  INTERNAL: "OFFERWALLME_INTERNAL_ERROR",
  MAINTENANCE: "OFFERWALL_MAINTENANCE",
  POSTBACK_FAILED: "OFFERWALLME_POSTBACK_FAILED",
  HISTORY_FAILED: "OFFERWALLME_HISTORY_FAILED",
  STATS_FAILED: "OFFERWALLME_STATS_FAILED",
  EMBED_FAILED: "OFFERWALLME_EMBED_FAILED",
  LINK_FAILED: "OFFERWALLME_LINK_FAILED",
} as const;

export type OfferwallMeErrorCode = (typeof OFFERWALLME_ERROR)[keyof typeof OFFERWALLME_ERROR];
