import express from "express";
import { requireAdminAuth } from "../admin/admin.auth.middleware.js";
import { createRateLimiter } from "../../core/http/middleware/rateLimit.js";
import * as ctrl from "./broadcast.controller.js";
export const broadcastAdminRouter = express.Router();
const adminLimiter = createRateLimiter({ windowMs: 60_000, max: 300 });
broadcastAdminRouter.use(requireAdminAuth, adminLimiter);
broadcastAdminRouter.post("/broadcast/upload-image", ctrl.uploadBroadcastImage);
broadcastAdminRouter.get("/broadcast", ctrl.adminListBroadcasts);
broadcastAdminRouter.post("/broadcast", ctrl.adminCreateBroadcast);
broadcastAdminRouter.patch("/broadcast/:id", ctrl.adminPatchBroadcast);
broadcastAdminRouter.delete("/broadcast/:id", ctrl.adminDeleteBroadcast);
