import express from "express";
import { requireAdminAuth } from "../admin/admin.auth.middleware.js";
import { createRateLimiter } from "../../core/http/middleware/rateLimit.js";
import * as ctrl from "./telegram.controller.js";
export const telegramAdminRouter = express.Router();
const adminLimiter = createRateLimiter({ windowMs: 60_000, max: 300 });
telegramAdminRouter.use(requireAdminAuth, adminLimiter);
telegramAdminRouter.get("/withdrawals/telegram-settings", ctrl.getSettings);
telegramAdminRouter.put("/withdrawals/telegram-settings", ctrl.putSettings);
telegramAdminRouter.get("/finance/telegram/settings", ctrl.getSettings);
telegramAdminRouter.patch("/finance/telegram/settings", ctrl.patchSettings);
telegramAdminRouter.post("/finance/telegram/test-private-alert", ctrl.testPrivateAlert);
telegramAdminRouter.post("/finance/telegram/test-public-proof", ctrl.testPublicProof);
telegramAdminRouter.get("/finance/telegram/events", ctrl.listEvents);
telegramAdminRouter.post("/finance/telegram/events/:id/retry", ctrl.retryEvent);
telegramAdminRouter.get("/finance/telegram/health", ctrl.getHealth);
