export const ROOMS_ERROR = {
  MAX_ROOMS_REACHED: "MAX_ROOMS_REACHED",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  RACK_OCCUPIED: "RACK_OCCUPIED",
  RACK_EMPTY: "RACK_EMPTY",
  ROW_EDGE_NO_SPACE: "ROW_EDGE_NO_SPACE",
  NO_SPACE: "NO_SPACE",
  ADJACENT_RACK_OCCUPIED: "ADJACENT_RACK_OCCUPIED",
} as const;
